// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package try

import (
	"github.com/google/wire"
)

// Injectors from wire-demo-1.go:

func InitializeWire1() (string, error) {
	myFooer := provideMyFooer()
	string2 := provideBar(myFooer)
	return string2, nil
}

// Injectors from wire-demo.go:

func InitializeEvent(msg string, code int) (*Event, error) {
	message := NewMessage(msg)
	operator := NewOperator(message, code)
	event := NewEvent(operator)
	return event, nil
}

// wire-demo-1.go:

type Fooer interface {
	Foo() string
}

type MyFooer string

func (b *MyFooer) Foo() string {
	return string(*b)
}

func provideMyFooer() *MyFooer {
	b := new(MyFooer)
	*b = "Hello, World!"
	return b
}

type Bar string

func provideBar(f Fooer) string {

	return f.Foo()
}

// WireSet 函数调用链
var WireSet = wire.NewSet(
	provideMyFooer, wire.Bind(new(Fooer), new(*MyFooer)), provideBar,
)
