// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"project-practice/internal/weekly-task/biz"
	"project-practice/internal/weekly-task/conf"
	"project-practice/internal/weekly-task/data"
	"project-practice/internal/weekly-task/server"
	"project-practice/internal/weekly-task/service"
)

// Injectors from wire.go:

func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	userService := service.NewCartService(userUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, userService)
	grpcServer := server.NewGRPCServer(confServer, userService)
	registrar := server.NewRegistrar(registry)
	app := newApp(confServer, logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
